
// import orders 
export const IMPORT_ORDER_REQUEST = "IMPORT_ORDER_REQUEST";
export const IMPORT_ORDER_PROGRESS = "IMPORT_ORDER_PROGRESS";
export const IMPORT_ORDER_SUCCESS = "IMPORT_ORDER_SUCCESS";
export const IMPORT_ORDER_FAILURE = "IMPORT_ORDER_FAILURE";