/**
 * =================== FETCH USERS ===================
 */

export const REQUEST_FETCH_USERS = "REQUEST_FETCH_USERS";
export const REQUEST_SUCCESS_USERS = "REQUEST_SUCCESS_USERS";
export const REQUEST_FAILURE_USERS = "REQUEST_FAILURE_USERS";
export const REQUEST_PROGRESS_USERS = "REQUEST_PROGRESS_USERS";

/**
 * =================== ADD USER ===================
 */

export const REQUEST_CREATE_USER = "REQUEST_CREATE_USER";
export const REQUEST_SUCCESS_CREATE_USER = "REQUEST_SUCCESS_CREATE_USER";
export const REQUEST_FAILURE_CREATE_USER = "REQUEST_FAILURE_CREATE_USER";
export const REQUEST_PROGRESS_CREATE_USER = "REQUEST_PROGRESS_CREATE_USER";

/**
 * =================== EDIT USER ===================
 */

export const REQUEST_EDIT_USER = "REQUEST_EDIT_USER";
export const REQUEST_SUCCESS_EDIT_USER = "REQUEST_SUCCESS_EDIT_USER";
export const REQUEST_FAILURE_EDIT_USER = "REQUEST_FAILURE_EDIT_USER";
export const REQUEST_PROGRESS_EDIt_USER = "REQUEST_PROGRESS_EDIt_USER";


/**
 * =================== DISABLE USER ===================
 */

export const REQUEST_DISABLE_USER = "REQUEST_DISABLE_USER";
export const REQUEST_SUCCESS_DISABLE_USER = "REQUEST_SUCCESS_DISABLE_USER";
export const REQUEST_FAILURE_DISABLE_USER = "REQUEST_FAILURE_DISABLE_USER";
export const REQUEST_PROGRESS_DISABLE_USER = "REQUEST_PROGRESS_DISABLE_USER";